
-- 2. create Books Table 
CREATE TABLE Books (
    Book_ID INT PRIMARY KEY,
    Title VARCHAR(255),
    Author VARCHAR(255),
    Genre VARCHAR(100),
    Published_Year INT,
    Price NUMERIC(10, 2),
    Stock INT
);

-- 3. Customers Table 
CREATE TABLE Customers (
    Customer_ID INT PRIMARY KEY,
    Name VARCHAR(255),
    Email VARCHAR(255),
    Phone BIGINT, 
    City VARCHAR(100),
    Country VARCHAR(100)
);

-- 4. Orders Table 
CREATE TABLE Orders (
    Order_ID INT PRIMARY KEY,
    Customer_ID INT,
    Book_ID INT,
    Order_Date DATE,
    Quantity INT,

    CONSTRAINT fk_customer FOREIGN KEY (Customer_ID) REFERENCES Customers(Customer_ID),
    CONSTRAINT fk_book FOREIGN KEY (Book_ID) REFERENCES Books(Book_ID)
);






 -- 1. Retrieve all books belonging to the "Fiction" genre.

 	SELECT book_id,title AS Book_name
	 	FROM books
		 WHERE genre = 'Fiction';


 -- 2. List of books published after the year 1950, sorted by publication year.

 	SELECT book_id,title,published_year
	 	FROM books
		 WHERE published_year > 1950
		 	ORDER BY published_year;

-- 3. Identifying the Top 5 most expensive books in the store.

	SELECT title AS Books,price
		FROM books
			ORDER BY price DESC
				LIMIT 5;


-- 4. books with stock levels below 10 units (Restock Alert).

	SELECT book_id,title AS book,stock
		FROM books
			WHERE stock <10
				ORDER BY stock;


--5. Count of total number of unique customers registered.

	SELECT  COUNT(DISTINCT(customer_id))
		AS Total_customers
			FROM customers;
			

-- 6. Calculate the Total Revenue generated by each Genre.

	SELECT b.genre,SUM(o.total_amount) AS Total_Revenue
		FROM books b LEFT JOIN orders o
			ON b.book_id = o.book_id
				GROUP BY b.genre
					ORDER BY SUM(o.total_amount) DESC;
					

-- 7. Identify the Total Amount spent by each individual Customer.

	SELECT c.customer_id, c.name, COALESCE(SUM(o.total_amount), 0) AS Total_Amount
		FROM customers c LEFT JOIN orders o
			ON c.customer_id = o.customer_id
				GROUP BY c.customer_id
					ORDER BY c.customer_id;


-- 8. List detailed Order Information, including Customer Name and Book Title.

	SELECT  o.customer_id,
			 c.name AS Customer_Name,
			 b.title AS Book_title,
			 o.quantity,
			 o.order_date 
				FROM orders o  JOIN  books b 
					ON o.order_id = b.book_id
					 JOIN customers c 
						ON o.customer_id = c.customer_id;


-- 9. Find the Most 5 Popular Author based on the total quantity of books sold.

	SELECT 
		b.author,
		COALESCE(SUM(o.quantity),0) AS Total_Quantity 
		  FROM orders o JOIN books b
		  	ON o.book_id = b.book_id
			  GROUP BY b.author
			  	ORDER BY SUM(o.quantity) DESC
				  LIMIT 5;


-- 10. Identify Customers who have never placed an order (Lead Generation).

	SELECT 
		c.customer_id,
		c.name AS Customer_name
		  FROM customers c  LEFT JOIN orders o 
		    ON o.customer_id = c.customer_id
			  WHERE o.quantity IS NULL; 


-- 11. Rank Books by Price within each Genre.


	SELECT title, genre, price,
		DENSE_RANK () OVER (PARTITION BY genre ORDER BY price DESC) AS Price_Rank
			FROM books;


-- 12. Calculate the Cumulative (Running Total) Revenue over time.

	SELECT order_date, total_amount,
		SUM(total_amount) OVER (ORDER BY order_date) AS Total_Revenue
			FROM orders;


-- 13. Find the Top-Spending Customer in every City

WITH Customer_Spending AS (
	SELECT
		c.customer_id, c.city,c.name AS Customer_Name,
		SUM(o.total_amount) AS Total_Spend,
		RANK() OVER(PARTITION BY c.city ORDER BY SUM(o.total_amount) DESC) AS Spending_Rank
			FROM customers c LEFT JOIN orders o 
				ON c.customer_id = o.customer_id
		
			GROUP BY c.customer_id,c.city, c.name
		)
		SELECT city,Customer_Name,Total_Spend
			FROM Customer_Spending
				WHERE Spending_Rank = 1
					ORDER BY total_spend DESC;


-- 14. Segment Customers into 'VIP', 'Regular', and 'New' based on total spending.					
			
	 SELECT
	 	customer_id,
		SUM(total_amount) AS Total_Spend,
			CASE 
			 WHEN SUM(total_amount)>200 THEN 'VIP'
			 WHEN SUM(total_amount) BETWEEN 100 AND 200 THEN 'Reguler'
		     ELSE 'New'
			 END AS customer_segment
			 FROM orders
			 GROUP BY customer_id;


-- 15. Calculate the Month-over-Month (MoM) Percentage Growth in Revenue.			 

	WITH monthly_Revenue AS (
		SELECT 
			DATE_TRUNC('month' ,order_date) AS Months,
			SUM(total_amount) AS Revenue
				FROM orders
				GROUP BY DATE_TRUNC('month' ,order_date)
	 	)

SELECT 
    Months,
    Revenue,
    	LAG(Revenue) OVER (ORDER BY Months) AS Previous_Month,
  
           ROUND(((Revenue - LAG(Revenue) OVER (ORDER BY Months)) / LAG(Revenue) OVER (ORDER BY Months)) * 100, 2) AS Growth_Percentage

				FROM monthly_Revenue;

	

			
			  


					
				
				